//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.21 at 09:56:24 PM CEST 
//


package OgameApi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="speedFleet" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="galaxies" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="systems" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="acs" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="rapidFire" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="defToTF" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="debrisFactor" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="repairFactor" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="newbieProtectionLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="newbieProtectionHigh" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="topScore" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="bonusFields" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="donutGalaxy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="donutSystem" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="serverId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "number",
    "language",
    "timezone",
    "domain",
    "version",
    "speed",
    "speedFleet",
    "galaxies",
    "systems",
    "acs",
    "rapidFire",
    "defToTF",
    "debrisFactor",
    "repairFactor",
    "newbieProtectionLimit",
    "newbieProtectionHigh",
    "topScore",
    "bonusFields",
    "donutGalaxy",
    "donutSystem"
})
@XmlRootElement(name = "serverData")
public class ServerData {

    protected String name;
    @XmlElement(required = true)
    protected String number;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected String timezone;
    @XmlElement(required = true)
    protected String domain;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected BigInteger speed;
    @XmlElement(required = true)
    protected BigInteger speedFleet;
    @XmlElement(required = true)
    protected BigInteger galaxies;
    @XmlElement(required = true)
    protected BigInteger systems;
    protected boolean acs;
    protected boolean rapidFire;
    protected boolean defToTF;
    protected float debrisFactor;
    protected float repairFactor;
    protected int newbieProtectionLimit;
    protected int newbieProtectionHigh;
    protected float topScore;
    protected int bonusFields;
    protected boolean donutGalaxy;
    protected boolean donutSystem;
    @XmlAttribute(name = "timestamp")
    protected BigInteger timestamp;
    @XmlAttribute(name = "serverId")
    protected String serverId;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimezone(String value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpeed(BigInteger value) {
        this.speed = value;
    }

    /**
     * Gets the value of the speedFleet property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpeedFleet() {
        return speedFleet;
    }

    /**
     * Sets the value of the speedFleet property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpeedFleet(BigInteger value) {
        this.speedFleet = value;
    }

    /**
     * Gets the value of the galaxies property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGalaxies() {
        return galaxies;
    }

    /**
     * Sets the value of the galaxies property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGalaxies(BigInteger value) {
        this.galaxies = value;
    }

    /**
     * Gets the value of the systems property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSystems() {
        return systems;
    }

    /**
     * Sets the value of the systems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSystems(BigInteger value) {
        this.systems = value;
    }

    /**
     * Gets the value of the acs property.
     * 
     */
    public boolean isAcs() {
        return acs;
    }

    /**
     * Sets the value of the acs property.
     * 
     */
    public void setAcs(boolean value) {
        this.acs = value;
    }

    /**
     * Gets the value of the rapidFire property.
     * 
     */
    public boolean isRapidFire() {
        return rapidFire;
    }

    /**
     * Sets the value of the rapidFire property.
     * 
     */
    public void setRapidFire(boolean value) {
        this.rapidFire = value;
    }

    /**
     * Gets the value of the defToTF property.
     * 
     */
    public boolean isDefToTF() {
        return defToTF;
    }

    /**
     * Sets the value of the defToTF property.
     * 
     */
    public void setDefToTF(boolean value) {
        this.defToTF = value;
    }

    /**
     * Gets the value of the debrisFactor property.
     * 
     */
    public float getDebrisFactor() {
        return debrisFactor;
    }

    /**
     * Sets the value of the debrisFactor property.
     * 
     */
    public void setDebrisFactor(float value) {
        this.debrisFactor = value;
    }

    /**
     * Gets the value of the repairFactor property.
     * 
     */
    public float getRepairFactor() {
        return repairFactor;
    }

    /**
     * Sets the value of the repairFactor property.
     * 
     */
    public void setRepairFactor(float value) {
        this.repairFactor = value;
    }

    /**
     * Gets the value of the newbieProtectionLimit property.
     * 
     */
    public int getNewbieProtectionLimit() {
        return newbieProtectionLimit;
    }

    /**
     * Sets the value of the newbieProtectionLimit property.
     * 
     */
    public void setNewbieProtectionLimit(int value) {
        this.newbieProtectionLimit = value;
    }

    /**
     * Gets the value of the newbieProtectionHigh property.
     * 
     */
    public int getNewbieProtectionHigh() {
        return newbieProtectionHigh;
    }

    /**
     * Sets the value of the newbieProtectionHigh property.
     * 
     */
    public void setNewbieProtectionHigh(int value) {
        this.newbieProtectionHigh = value;
    }

    /**
     * Gets the value of the topScore property.
     * 
     */
    public float getTopScore() {
        return topScore;
    }

    /**
     * Sets the value of the topScore property.
     * 
     */
    public void setTopScore(float value) {
        this.topScore = value;
    }

    /**
     * Gets the value of the bonusFields property.
     * 
     */
    public int getBonusFields() {
        return bonusFields;
    }

    /**
     * Sets the value of the bonusFields property.
     * 
     */
    public void setBonusFields(int value) {
        this.bonusFields = value;
    }

    /**
     * Gets the value of the donutGalaxy property.
     * 
     */
    public boolean isDonutGalaxy() {
        return donutGalaxy;
    }

    /**
     * Sets the value of the donutGalaxy property.
     * 
     */
    public void setDonutGalaxy(boolean value) {
        this.donutGalaxy = value;
    }

    /**
     * Gets the value of the donutSystem property.
     * 
     */
    public boolean isDonutSystem() {
        return donutSystem;
    }

    /**
     * Sets the value of the donutSystem property.
     * 
     */
    public void setDonutSystem(boolean value) {
        this.donutSystem = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimestamp(BigInteger value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the serverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * Sets the value of the serverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerId(String value) {
        this.serverId = value;
    }

}
